---
language: go
go:
  - 1.13.x
notifications:
  irc: "chat.freenode.net#openshift-dev"
matrix:
  allow_failures:
    - go: master
  fast_finish: true
services:
  - docker
env:
  global:
    - S2I_GIT_VERSION=""
    - S2I_GIT_MAJOR=""
    - S2I_GIT_MINOR=""
install:
  - make install-travis
script:
  # running project linting, static tests
  - GOFLAGS="-mod=vendor" make verify
  # running unit tests
  - GOFLAGS="-mod=vendor" make test TESTFLAGS="-p=4" TESTS="''" # empty quotes are because hack/test-go.sh requires 2 args
  # build image from current branch
  - make image && docker images && make test-image

